# Generated by Django 3.2.4 on 2021-09-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
