# Generated by Django 3.2.4 on 2021-09-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='date',
            new_name='dob',
        ),
    ]
