# Generated by Django 3.2.4 on 2021-10-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211008_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='addinfo',
            name='is_submittedd',
            field=models.BooleanField(default=False),
        ),
    ]
