# Generated by Django 3.2.4 on 2021-10-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_addinfo_is_submittedd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addinfo',
            old_name='is_submittedd',
            new_name='is_submitted',
        ),
    ]
